name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build web app
      - name: Build web app
        run: npm run build

      # Setup Java 17
      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Sync Capacitor Android
      - name: Sync Capacitor Android
        run: npx cap sync android

      # Make Gradlew executable
      - name: Make Gradlew Executable
        run: chmod +x android/gradlew

      # Build Debug APK
      - name: Build Debug APK
        run: cd android && ./gradlew assembleDebug

      # Upload Debug APK
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

      # Build Release APK (unsigned)
      - name: Build Release APK
        run: cd android && ./gradlew assembleRelease

      # Upload Release APK (unsigned)
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned.apk
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk
          
