name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4   # Updated to v4

    - name: Setup Node.js
      uses: actions/setup-node@v4   # Updated to v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build web app
      run: npm run build

    - name: Setup Java
      uses: actions/setup-java@v4   # Updated to v4
      with:
        distribution: 'temurin'     # Updated from zulu to temurin (recommended)
        java-version: '17'          # Updated to Java 17 for Android builds

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3   # Updated to v3

    - name: Sync Capacitor
      run: npx cap sync android

    - name: Build Debug APK
      run: |
        cd android
        chmod +x ./gradlew
        ./gradlew assembleDebug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4   # Updated to v4
      with:
        name: pall-network-debug.apk
        path: android/app/build/outputs/apk/debug/app-debug.apk

    - name: Build Release APK (if needed)
      run: |
        cd android
        chmod +x ./gradlew
        ./gradlew assembleRelease
      continue-on-error: true

    - name: Upload Release APK
      uses: actions/upload-artifact@v4   # Updated to v4
      with:
        name: pall-network-release.apk
        path: android/app/build/outputs/apk/release/app-release-unsigned.apk
      continue-on-error: true
