# Upload Debug APK
- name: Upload Debug APK
  uses: actions/upload-artifact@v4
  with:
    name: app-debug.apk
    path: android/app/build/outputs/apk/debug/app-debug.apk

# Upload Release APK (unsigned)
- name: Upload Release APK
  uses: actions/upload-artifact@v4
  with:
    name: app-release-unsigned.apk
    path: android/app/build/outputs/apk/release/app-release-unsigned.apk
