name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build web app
      run: npm run build

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Sync Capacitor
      run: npx cap sync android

    - name: Build APK
      run: |
        cd android
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: pall-network-debug.apk
        path: android/app/build/outputs/apk/debug/app-debug.apk

    - name: Build Release APK (if needed)
      run: |
        cd android
        ./gradlew assembleRelease
      continue-on-error: true

    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: pall-network-release.apk
        path: android/app/build/outputs/apk/release/app-release-unsigned.apk
      continue-on-error: true