name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Java (required for Android builds)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Give Gradle permission to run
      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      # Build the APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-android-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      
