name: Build Android Signed APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > my-release-key.jks

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
          -keystore my-release-key.jks \
          -storepass ${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
          -keypass ${{ secrets.ANDROID_KEY_PASSWORD }} \
          app/build/outputs/apk/release/app-release-unsigned.apk \
          ${{ secrets.ANDROID_KEY_ALIAS }}

      - name: Zipalign APK
        run: |
          $ANDROID_SDK_ROOT/build-tools/34.0.0/zipalign -v -p 4 \
          app/build/outputs/apk/release/app-release-unsigned.apk \
          app-release-signed.apk

      - name: Verify Signed APK
        run: |
          jarsigner -verify app-release-signed.apk

      - name: Upload Signed APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-signed
          path: app-release-signed.apk
